export function generateContext(persona) {
    // Simple logic for now, can be expanded
    return persona.default_context;
}

export function generatePrimaryNeed(persona) {
    if (persona.surface_traits.includes('Price-sensitive')) return 'Price/Value';
    if (persona.surface_traits.includes('Tech-oriented')) return 'Picture Quality/Specs';
    if (persona.surface_traits.includes('Gamer-oriented')) return 'Gaming Performance';
    if (persona.surface_traits.includes('Design-focused')) return 'Aesthetics/Design';
    if (persona.surface_traits.includes('Durability-focused')) return 'Durability/Warranty';
    if (persona.surface_traits.includes('Environment-sensitive')) return 'Brightness/Reflection';
    return 'General Usage';
}

export function generatePainPoint(persona) {
    if (persona.hidden_traits.price_resistance === 'extreme') return 'Budget constraints';
    if (persona.hidden_traits.technical_depth === 'expert') return 'Technical skepticism';
    if (persona.hidden_traits.scenario_bias?.includes('durability')) return 'Fear of breakdown/Burn-in';
    if (persona.hidden_traits.scenario_bias?.includes('brightness')) return 'Room is too bright';
    if (persona.hidden_traits.skepticism_level === 'high') return 'Trust issues/Bad past experience';
    return 'Indecision';
}

export function generateOpeningLine(persona, difficulty) {
    // This should ideally be generated by AI or a more complex template system
    // For now, returning a placeholder that the AI will use to generate the actual speech
    return `[System: Generate an opening line for ${persona.name} with tone "${persona.default_tone}" and difficulty ${difficulty.label}]`;
}
