import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { operatorApi } from '../../services/operatorApi';
import { FileText, Video, Link as LinkIcon, Upload, Play, Brain, CheckCircle, Clock, AlertCircle } from 'lucide-react';
import { clsx } from 'clsx';

export default function ContentManager() {
    const navigate = useNavigate();
    const [materials, setMaterials] = useState([]);
    const [loading, setLoading] = useState(true);
    const [uploading, setUploading] = useState(false);
    const [selectedMaterial, setSelectedMaterial] = useState(null);
    const fileInputRef = React.useRef(null);

    useEffect(() => {
        loadMaterials();
    }, []);

    const loadMaterials = async () => {
        setLoading(true);
        const res = await operatorApi.getMaterials();
        if (res.success) {
            setMaterials(res.data.materials);
        }
        setLoading(false);
    };

    const handleFileUpload = async (e) => {
        // Mock file upload
        const file = e.target.files[0];
        if (!file) return;

        setUploading(true);
        // Simulate upload delay
        await new Promise(r => setTimeout(r, 1000));

        const newMat = {
            title: file.name.split('.')[0],
            description: "Uploaded via Console",
            type: file.type.includes('pdf') ? 'pdf' : 'video',
            category: 'product',
            tags: ['upload'],
            file: { fileName: file.name, fileSize: file.size }
        };

        const res = await operatorApi.createMaterial(newMat);
        if (res.success) {
            setMaterials([...materials, res.data.material]);
            // Simulate waiting for AI processing
            setTimeout(loadMaterials, 2500);
        }
        setUploading(false);
        // Reset input
        if (fileInputRef.current) fileInputRef.current.value = '';
    };

    return (
        <div className="flex h-[calc(100vh-100px)] gap-6">
            {/* Left: Material List */}
            <div className="w-1/3 flex flex-col bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                <div className="p-4 border-b border-slate-100 bg-slate-50 flex justify-between items-center">
                    <h3 className="font-bold text-slate-800">Study Materials</h3>
                    <button
                        onClick={() => fileInputRef.current?.click()}
                        className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 text-white text-xs font-bold rounded-lg hover:bg-indigo-700 transition-colors"
                        disabled={uploading}
                    >
                        <Upload size={14} />
                        {uploading ? 'Uploading...' : 'Upload'}
                    </button>
                    <input
                        type="file"
                        className="hidden"
                        ref={fileInputRef}
                        onChange={handleFileUpload}
                        disabled={uploading}
                    />
                </div>

                <div className="flex-1 overflow-y-auto p-2 space-y-2">
                    {loading ? <div className="p-4 text-center text-slate-400">Loading...</div> : materials.map(mat => (
                        <div
                            key={mat.materialId}
                            onClick={() => setSelectedMaterial(mat)}
                            className={clsx(
                                "p-3 rounded-lg border cursor-pointer transition-all flex gap-3 items-start",
                                selectedMaterial?.materialId === mat.materialId
                                    ? "bg-indigo-50 border-indigo-200 shadow-sm"
                                    : "bg-white border-slate-100 hover:border-slate-300"
                            )}
                        >
                            <div className={clsx(
                                "w-10 h-10 rounded-lg flex items-center justify-center shrink-0",
                                mat.type === 'pdf' ? "bg-red-50 text-red-600" :
                                    mat.type === 'video' ? "bg-blue-50 text-blue-600" : "bg-slate-50 text-slate-600"
                            )}>
                                {mat.type === 'pdf' ? <FileText size={20} /> : mat.type === 'video' ? <Video size={20} /> : <LinkIcon size={20} />}
                            </div>
                            <div className="flex-1 min-w-0">
                                <h4 className="font-bold text-slate-800 text-sm truncate">{mat.title}</h4>
                                <div className="flex items-center gap-2 mt-1">
                                    <span className="text-xs text-slate-500 capitalize">{mat.category}</span>
                                    {mat.autoGeneratedModule?.status === 'completed' && (
                                        <span className="flex items-center gap-1 text-[10px] font-bold text-green-600 bg-green-50 px-1.5 py-0.5 rounded">
                                            <Brain size={10} /> AI Ready
                                        </span>
                                    )}
                                    {mat.autoGeneratedModule?.status === 'pending' && (
                                        <span className="flex items-center gap-1 text-[10px] font-bold text-amber-600 bg-amber-50 px-1.5 py-0.5 rounded animate-pulse">
                                            <Clock size={10} /> Processing
                                        </span>
                                    )}
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Right: Content Preview & AI Status */}
            <div className="flex-1 bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden flex flex-col">
                {selectedMaterial ? (
                    <div className="flex flex-col h-full">
                        <div className="p-6 border-b border-slate-100">
                            <div className="flex items-start justify-between">
                                <div>
                                    <h2 className="text-xl font-bold text-slate-900">{selectedMaterial.title}</h2>
                                    <p className="text-slate-500 text-sm mt-1">{selectedMaterial.description}</p>
                                </div>
                                <div className="flex gap-2">
                                    {selectedMaterial.tags.map(tag => (
                                        <span key={tag} className="px-2 py-1 bg-slate-100 text-slate-600 text-xs rounded font-medium">#{tag}</span>
                                    ))}
                                </div>
                            </div>
                        </div>

                        <div className="flex-1 p-6 overflow-y-auto">
                            {/* AI Extraction Status */}
                            <div className="mb-8">
                                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 flex items-center gap-2">
                                    <Brain size={16} className="text-indigo-600" />
                                    AI Content Extraction
                                </h3>

                                {selectedMaterial.autoGeneratedModule?.status === 'completed' ? (
                                    <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-5">
                                        <div className="flex items-center gap-2 text-indigo-700 font-bold mb-2">
                                            <CheckCircle size={18} />
                                            Extraction Complete
                                        </div>
                                        <p className="text-sm text-indigo-600 mb-4">
                                            Successfully generated training module <strong>{selectedMaterial.autoGeneratedModule.moduleId}</strong>.
                                        </p>
                                        <button
                                            onClick={() => window.location.href = `#/admin/cms/quiz?id=${selectedMaterial.autoGeneratedModule.moduleId}&materialId=${selectedMaterial.materialId}`}
                                            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-bold rounded-lg transition-colors shadow-sm"
                                        >
                                            Review Training Module
                                        </button>

                                        {/* QA Verification Button */}
                                        <button
                                            onClick={async () => {
                                                await operatorApi.updateMaterial(selectedMaterial.materialId, { title: selectedMaterial.title + " (v2)" });
                                                loadMaterials(); // Refresh list
                                            }}
                                            className="ml-2 px-4 py-2 bg-gray-800 text-white text-sm font-bold rounded-lg"
                                        >
                                            Simulate v2 Update
                                        </button>
                                    </div>
                                ) : (
                                    <div className="bg-amber-50 border border-amber-100 rounded-xl p-5">
                                        <div className="flex items-center gap-2 text-amber-700 font-bold mb-2">
                                            <Clock size={18} className="animate-spin" />
                                            AI Processing in Progress...
                                        </div>
                                        <p className="text-sm text-amber-600">
                                            Analyzing document structure, extracting key concepts, and generating quiz questions.
                                        </p>
                                    </div>
                                )}
                            </div>

                            {/* File Meta */}
                            <div>
                                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4">Source File</h3>
                                <div className="bg-slate-50 border border-slate-200 rounded-lg p-4 flex items-center gap-4">
                                    <div className="w-12 h-12 bg-white rounded-lg border border-slate-200 flex items-center justify-center text-slate-400">
                                        {selectedMaterial.type === 'pdf' ? <FileText size={24} /> : <Video size={24} />}
                                    </div>
                                    <div>
                                        <div className="font-mono text-sm text-slate-700">{selectedMaterial.file.fileName}</div>
                                        <div className="text-xs text-slate-400">{(selectedMaterial.file.fileSize / 1024 / 1024).toFixed(2)} MB</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center h-full text-slate-400">
                        <FileText size={48} className="mb-4 opacity-20" />
                        <p>Select a material to preview</p>
                    </div>
                )}
            </div>
        </div>
    );
}
